# Cloud Build configuration for CHALDEAS
# Builds and deploys both backend and frontend to Cloud Run

substitutions:
  _REGION: asia-northeast3  # Seoul region
  _BACKEND_SERVICE: chaldeas-backend
  _FRONTEND_SERVICE: chaldeas-frontend
  _CLOUD_SQL_INSTANCE: ${PROJECT_ID}:${_REGION}:chaldeas-db

steps:
  # ============================================
  # Step 1: Build Backend Image
  # ============================================
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/${_BACKEND_SERVICE}:${COMMIT_SHA}'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/${_BACKEND_SERVICE}:latest'
      - '-f'
      - 'backend/Dockerfile.prod'
      - 'backend'
    id: 'build-backend'

  # ============================================
  # Step 2: Build Frontend Image
  # ============================================
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/${_FRONTEND_SERVICE}:${COMMIT_SHA}'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/${_FRONTEND_SERVICE}:latest'
      - '-f'
      - 'frontend/Dockerfile.prod'
      - '--build-arg'
      - 'VITE_API_URL=${_BACKEND_URL}'
      - 'frontend'
    id: 'build-frontend'
    waitFor: ['-']  # Run in parallel with backend build

  # ============================================
  # Step 3: Push Backend Image
  # ============================================
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/${PROJECT_ID}/${_BACKEND_SERVICE}:${COMMIT_SHA}'
    id: 'push-backend'
    waitFor: ['build-backend']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/${PROJECT_ID}/${_BACKEND_SERVICE}:latest'
    waitFor: ['push-backend']

  # ============================================
  # Step 4: Push Frontend Image
  # ============================================
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/${PROJECT_ID}/${_FRONTEND_SERVICE}:${COMMIT_SHA}'
    id: 'push-frontend'
    waitFor: ['build-frontend']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/${PROJECT_ID}/${_FRONTEND_SERVICE}:latest'
    waitFor: ['push-frontend']

  # ============================================
  # Step 5: Deploy Backend to Cloud Run
  # ============================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_BACKEND_SERVICE}'
      - '--image'
      - 'gcr.io/${PROJECT_ID}/${_BACKEND_SERVICE}:${COMMIT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'ENVIRONMENT=production'
      - '--set-secrets'
      - 'DATABASE_URL=chaldeas-database-url:latest,OPENAI_API_KEY=chaldeas-openai-key:latest,ANTHROPIC_API_KEY=chaldeas-anthropic-key:latest'
      - '--add-cloudsql-instances'
      - '${_CLOUD_SQL_INSTANCE}'
    id: 'deploy-backend'
    waitFor: ['push-backend']

  # ============================================
  # Step 6: Deploy Frontend to Cloud Run
  # ============================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_FRONTEND_SERVICE}'
      - '--image'
      - 'gcr.io/${PROJECT_ID}/${_FRONTEND_SERVICE}:${COMMIT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '256Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '5'
    id: 'deploy-frontend'
    waitFor: ['push-frontend', 'deploy-backend']

images:
  - 'gcr.io/${PROJECT_ID}/${_BACKEND_SERVICE}:${COMMIT_SHA}'
  - 'gcr.io/${PROJECT_ID}/${_BACKEND_SERVICE}:latest'
  - 'gcr.io/${PROJECT_ID}/${_FRONTEND_SERVICE}:${COMMIT_SHA}'
  - 'gcr.io/${PROJECT_ID}/${_FRONTEND_SERVICE}:latest'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'
