"""Add person_locations, location_relationships, location_sources tables

Revision ID: 655ce5c78189
Revises: fdbfd311bd05
Create Date: 2026-01-15 23:23:33.384850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '655ce5c78189'
down_revision: Union[str, None] = 'fdbfd311bd05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_relationships',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('related_location_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'related_location_id')
    )
    op.create_table('location_sources',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('page_reference', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'source_id')
    )
    op.drop_table('events_backup_20260108_171137')
    op.drop_table('events_backup_20260109_063310')
    op.drop_table('persons_backup_20260110_204240')
    op.drop_index('idx_event_aliases_1', table_name='event_aliases')
    op.drop_index('idx_event_aliases_2', table_name='event_aliases')
    op.drop_table('event_aliases')
    op.drop_table('locations_backup_20260110_203224')
    op.drop_table('events_backup_20260108_080905')
    op.drop_index('idx_conn_direction', table_name='event_connections')
    op.drop_index('idx_conn_events', table_name='event_connections')
    op.drop_index('idx_conn_layer', table_name='event_connections')
    op.drop_index('idx_conn_strength', table_name='event_connections')
    op.drop_index('idx_conn_verification', table_name='event_connections')
    op.drop_table('event_connections')
    op.drop_index('idx_gazetteer_name_norm', table_name='gazetteer')
    op.drop_index('idx_gazetteer_source', table_name='gazetteer')
    op.drop_table('gazetteer')
    op.drop_index('embeddings_content_idx', table_name='embeddings')
    op.drop_table('embeddings')
    op.drop_index('idx_connsrc_connection', table_name='connection_sources')
    op.drop_index('idx_connsrc_source', table_name='connection_sources')
    op.drop_table('connection_sources')
    op.alter_column('chain_entity_roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.create_index(op.f('ix_chain_entity_roles_id'), 'chain_entity_roles', ['id'], unique=False)
    op.alter_column('chain_segments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.create_index(op.f('ix_chain_segments_id'), 'chain_segments', ['id'], unique=False)
    op.alter_column('entity_aliases', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.create_index('idx_alias_lookup', 'entity_aliases', ['alias'], unique=False)
    op.create_index(op.f('ix_entity_aliases_id'), 'entity_aliases', ['id'], unique=False)
    op.alter_column('event_relationships', 'certainty',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('event_relationships', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_event_rel_causal', table_name='event_relationships')
    op.alter_column('events', 'temporal_scale',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('events', 'certainty',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_events_enriched_by', table_name='events')
    op.drop_index('idx_events_enrichment_version', table_name='events')
    op.drop_index('idx_events_period_date', table_name='events')
    op.drop_index('idx_events_temporal_range', table_name='events')
    op.drop_index('ix_events_wikidata_id', table_name='events')
    op.create_index(op.f('ix_events_period_id'), 'events', ['period_id'], unique=False)
    op.drop_column('events', 'enrichment_version')
    op.drop_column('events', 'enriched_by')
    op.drop_column('events', 'wikidata_id')
    op.drop_column('events', 'embedding')
    op.drop_column('events', 'enriched_at')
    op.alter_column('historical_chains', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False)
    op.alter_column('historical_chains', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False)
    op.create_index(op.f('ix_historical_chains_id'), 'historical_chains', ['id'], unique=False)
    op.alter_column('import_batches', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('import_batches', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.create_index(op.f('ix_import_batches_id'), 'import_batches', ['id'], unique=False)
    op.drop_index('idx_locations_name_trgm', table_name='locations', postgresql_using='gin')
    op.drop_index('ix_locations_wikidata_id', table_name='locations')
    op.drop_column('locations', 'geocoded_at')
    op.drop_column('locations', 'wikidata_id')
    op.drop_column('locations', 'embedding')
    op.drop_column('locations', 'wikipedia_url')
    op.drop_column('locations', 'geocoded_by')
    op.alter_column('pending_entities', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.create_index(op.f('ix_pending_entities_id'), 'pending_entities', ['id'], unique=False)
    op.alter_column('periods', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False)
    op.alter_column('periods', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False)
    op.create_index(op.f('ix_periods_id'), 'periods', ['id'], unique=False)
    op.add_column('person_locations', sa.Column('confidence', sa.Float(), nullable=True))
    op.alter_column('person_locations', 'role',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_person_locations_location', table_name='person_locations')
    op.drop_index('idx_person_locations_person', table_name='person_locations')
    op.alter_column('person_relationships', 'strength',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('person_relationships', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('person_relationships', 'is_bidirectional',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.drop_column('person_relationships', 'time_distance')
    op.alter_column('persons', 'certainty',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('persons', 'mention_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('persons', 'avg_confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_persons_canonical_id', table_name='persons')
    op.drop_index('idx_persons_name_trgm', table_name='persons', postgresql_using='gin')
    op.create_index(op.f('ix_persons_canonical_id'), 'persons', ['canonical_id'], unique=False)
    op.drop_column('persons', 'enrichment_version')
    op.drop_column('persons', 'enriched_by')
    op.drop_column('persons', 'verified_at')
    op.drop_column('persons', 'source_type')
    op.drop_column('persons', 'data_quality')
    op.drop_column('persons', 'enriched_at')
    op.alter_column('polities', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False)
    op.alter_column('polities', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False)
    op.drop_index('idx_polities_embedding', table_name='polities', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index(op.f('ix_polities_id'), 'polities', ['id'], unique=False)
    op.drop_index('idx_sources_document_id', table_name='sources')
    op.create_index(op.f('ix_sources_archive_type'), 'sources', ['archive_type'], unique=False)
    op.create_index(op.f('ix_sources_document_id'), 'sources', ['document_id'], unique=False)
    op.drop_column('sources', 'content')
    op.alter_column('text_mentions', 'extracted_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.create_index(op.f('ix_text_mentions_id'), 'text_mentions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_text_mentions_id'), table_name='text_mentions')
    op.alter_column('text_mentions', 'extracted_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.add_column('sources', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_sources_document_id'), table_name='sources')
    op.drop_index(op.f('ix_sources_archive_type'), table_name='sources')
    op.create_index('idx_sources_document_id', 'sources', ['document_id'], unique=False)
    op.drop_index(op.f('ix_polities_id'), table_name='polities')
    op.create_index('idx_polities_embedding', 'polities', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('polities', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=True)
    op.alter_column('polities', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=True)
    op.add_column('persons', sa.Column('enriched_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='When enrichment was performed'))
    op.add_column('persons', sa.Column('data_quality', sa.VARCHAR(length=20), server_default=sa.text("'extracted'::character varying"), autoincrement=False, nullable=True))
    op.add_column('persons', sa.Column('source_type', sa.VARCHAR(length=20), server_default=sa.text("'ner'::character varying"), autoincrement=False, nullable=True))
    op.add_column('persons', sa.Column('verified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('persons', sa.Column('enriched_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='Model used for enrichment'))
    op.add_column('persons', sa.Column('enrichment_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='Enrichment pipeline version'))
    op.drop_index(op.f('ix_persons_canonical_id'), table_name='persons')
    op.create_index('idx_persons_name_trgm', 'persons', ['name'], unique=False, postgresql_using='gin')
    op.create_index('idx_persons_canonical_id', 'persons', ['canonical_id'], unique=False)
    op.alter_column('persons', 'avg_confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0.0'),
               existing_nullable=True)
    op.alter_column('persons', 'mention_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('persons', 'certainty',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'fact'::character varying"),
               existing_nullable=True)
    op.add_column('person_relationships', sa.Column('time_distance', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('person_relationships', 'is_bidirectional',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('person_relationships', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('1.0'),
               existing_nullable=True)
    op.alter_column('person_relationships', 'strength',
               existing_type=sa.INTEGER(),
               server_default=sa.text('3'),
               existing_nullable=True)
    op.create_index('idx_person_locations_person', 'person_locations', ['person_id'], unique=False)
    op.create_index('idx_person_locations_location', 'person_locations', ['location_id'], unique=False)
    op.alter_column('person_locations', 'role',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'associated'::character varying"),
               existing_nullable=True)
    op.drop_column('person_locations', 'confidence')
    op.drop_index(op.f('ix_periods_id'), table_name='periods')
    op.alter_column('periods', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=True)
    op.alter_column('periods', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=True)
    op.drop_index(op.f('ix_pending_entities_id'), table_name='pending_entities')
    op.alter_column('pending_entities', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.add_column('locations', sa.Column('geocoded_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='Model/service used for geocoding (e.g., pleiades, gpt-5.1)'))
    op.add_column('locations', sa.Column('wikipedia_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('locations', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=True))
    op.add_column('locations', sa.Column('wikidata_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('locations', sa.Column('geocoded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='When geocoding was performed'))
    op.create_index('ix_locations_wikidata_id', 'locations', ['wikidata_id'], unique=False)
    op.create_index('idx_locations_name_trgm', 'locations', ['name'], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_import_batches_id'), table_name='import_batches')
    op.alter_column('import_batches', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('import_batches', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.drop_index(op.f('ix_historical_chains_id'), table_name='historical_chains')
    op.alter_column('historical_chains', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=True)
    op.alter_column('historical_chains', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=True)
    op.add_column('events', sa.Column('enriched_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='When enrichment was performed'))
    op.add_column('events', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('wikidata_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('enriched_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='Model used for enrichment (e.g., gemma2:9b, gpt-5.1)'))
    op.add_column('events', sa.Column('enrichment_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='Enrichment pipeline version (e.g., v1.0, v2.0)'))
    op.drop_index(op.f('ix_events_period_id'), table_name='events')
    op.create_index('ix_events_wikidata_id', 'events', ['wikidata_id'], unique=False)
    op.create_index('idx_events_temporal_range', 'events', ['date_start', 'date_end'], unique=False)
    op.create_index('idx_events_period_date', 'events', ['period_id', 'date_start'], unique=False)
    op.create_index('idx_events_enrichment_version', 'events', ['enrichment_version'], unique=False)
    op.create_index('idx_events_enriched_by', 'events', ['enriched_by'], unique=False)
    op.alter_column('events', 'certainty',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'fact'::character varying"),
               existing_nullable=True)
    op.alter_column('events', 'temporal_scale',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'evenementielle'::character varying"),
               existing_nullable=True)
    op.create_index('idx_event_rel_causal', 'event_relationships', ['from_event_id', 'relationship_type'], unique=False)
    op.alter_column('event_relationships', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('1.0'),
               existing_nullable=True)
    op.alter_column('event_relationships', 'certainty',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'probable'::character varying"),
               existing_nullable=True)
    op.drop_index(op.f('ix_entity_aliases_id'), table_name='entity_aliases')
    op.drop_index('idx_alias_lookup', table_name='entity_aliases')
    op.alter_column('entity_aliases', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.drop_index(op.f('ix_chain_segments_id'), table_name='chain_segments')
    op.alter_column('chain_segments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.drop_index(op.f('ix_chain_entity_roles_id'), table_name='chain_entity_roles')
    op.alter_column('chain_entity_roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.create_table('connection_sources',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('connection_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mention_context', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('event_a_position', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_b_position', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('proximity_in_text', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['event_connections.id'], name='connection_sources_connection_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name='connection_sources_source_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='connection_sources_pkey')
    )
    op.create_index('idx_connsrc_source', 'connection_sources', ['source_id'], unique=False)
    op.create_index('idx_connsrc_connection', 'connection_sources', ['connection_id'], unique=False)
    op.create_table('embeddings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('content_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=3072), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='embeddings_pkey'),
    sa.UniqueConstraint('content_type', 'content_id', name='embeddings_content_type_content_id_key')
    )
    op.create_index('embeddings_content_idx', 'embeddings', ['content_type', 'content_id'], unique=False)
    op.create_table('gazetteer',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('name_normalized', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('place_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('population', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='gazetteer_pkey')
    )
    op.create_index('idx_gazetteer_source', 'gazetteer', ['source'], unique=False)
    op.create_index('idx_gazetteer_name_norm', 'gazetteer', ['name_normalized'], unique=False)
    op.create_table('event_connections',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_a_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_b_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('direction', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('layer_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('layer_entity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('connection_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('strength_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('source_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time_distance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('manual_strength', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('manual_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('verification_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('verified_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('verified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('curated_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('curated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('curated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('curation_note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_a_id'], ['events.id'], name='event_connections_event_a_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_b_id'], ['events.id'], name='event_connections_event_b_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='event_connections_pkey'),
    sa.UniqueConstraint('event_a_id', 'event_b_id', 'layer_type', name='uq_event_connection_layer')
    )
    op.create_index('idx_conn_verification', 'event_connections', ['verification_status'], unique=False)
    op.create_index('idx_conn_strength', 'event_connections', ['strength_score'], unique=False)
    op.create_index('idx_conn_layer', 'event_connections', ['layer_type', 'layer_entity_id'], unique=False)
    op.create_index('idx_conn_events', 'event_connections', ['event_a_id', 'event_b_id'], unique=False)
    op.create_index('idx_conn_direction', 'event_connections', ['direction'], unique=False)
    op.create_table('events_backup_20260108_080905',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('title_ko', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('slug', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description_ko', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date_start', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_start_month', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_start_day', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_end', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_end_month', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_end_day', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_precision', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('importance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('primary_location_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source_reliability', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('wikipedia_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=True),
    sa.Column('temporal_scale', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('period_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('certainty', sa.VARCHAR(length=20), autoincrement=False, nullable=True)
    )
    op.create_table('locations_backup_20260110_203224',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name_ko', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name_original', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.NUMERIC(precision=10, scale=8), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.NUMERIC(precision=11, scale=8), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('modern_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('region', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description_ko', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=True),
    sa.Column('hierarchy_level', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('modern_parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('historical_parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('valid_from', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('valid_until', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('geocoded_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('geocoded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    op.create_table('event_aliases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_id_1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_id_2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('similarity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id_1'], ['events.id'], name='event_aliases_event_id_1_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id_2'], ['events.id'], name='event_aliases_event_id_2_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='event_aliases_pkey'),
    sa.UniqueConstraint('event_id_1', 'event_id_2', name='event_aliases_event_id_1_event_id_2_key')
    )
    op.create_index('idx_event_aliases_2', 'event_aliases', ['event_id_2'], unique=False)
    op.create_index('idx_event_aliases_1', 'event_aliases', ['event_id_1'], unique=False)
    op.create_table('persons_backup_20260110_204240',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name_ko', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name_original', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('birth_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('birth_month', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('birth_day', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('death_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('death_month', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('death_day', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('birth_date_precision', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('death_date_precision', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('biography', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('biography_ko', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('birthplace_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deathplace_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('wikipedia_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=True),
    sa.Column('wikidata_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('canonical_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('era', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('floruit_start', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('floruit_end', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('certainty', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('primary_polity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mention_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('enriched_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('enriched_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('enrichment_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True)
    )
    op.create_table('events_backup_20260109_063310',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('title_ko', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('slug', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description_ko', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date_start', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_start_month', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_start_day', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_end', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_end_month', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_end_day', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_precision', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('importance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('primary_location_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source_reliability', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('wikipedia_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=True),
    sa.Column('temporal_scale', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('period_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('certainty', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('enriched_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('enriched_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('enrichment_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True)
    )
    op.create_table('events_backup_20260108_171137',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('title_ko', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('slug', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description_ko', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date_start', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_start_month', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_start_day', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_end', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_end_month', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_end_day', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_precision', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('importance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('primary_location_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source_reliability', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('wikipedia_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=True),
    sa.Column('temporal_scale', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('period_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('certainty', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('enriched_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('enriched_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('enrichment_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True)
    )
    op.drop_table('location_sources')
    op.drop_table('location_relationships')
    # ### end Alembic commands ###
